/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'CltControl' at '12/01/16 10:04' with Gradle 2.9
 *
 * @author CltControl, @date 12/01/16 10:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
